version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dev-deps:
        patterns:
          - "ruff"
          - "mypy"
          - "pytest*"
          - "python-semantic-release"
      ai-deps:
        patterns:
          - "groq"
          - "fastembed"
      cli-framework:
        patterns:
          - "typer"
          - "rich"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
